### PR TITLE
Bump ember-cordova-installer to latest version to support installation on node 8

### PR DESCRIPTION
**Pull request by jeanduplessis**

### CODE REVIEW

**Comment by rmachielse** [comment]
@jeanduplessis @alexblom I need this change as well. Any idea why the tests are failing?

**Comment by alexblom** [comment]
Unsure on the tests - taking a look today. Thanks for the PR!

**Comment by rmachielse** [comment]
@alexblom thanks for merging! Any chance of a release soon?

**Comment by alexblom** [comment]
Done - apologies. I'll figure out whats up with the tests in the next release.

**Comment by rmachielse** [comment]
Thanks!

**Pull request merged**
