### PR TITLE
Upgrade packages to latest ember LTS

### PR DESCRIPTION
**Pull request by rmachielse**
Supercedes #10

### CODE REVIEW

**Comment by rmachielse** [comment]
@alexblom I upgraded ember-cli to 2.18 (latest LTS) and adopted almost all changes from the blueprint. This also fixes the tests and the babel deprecation warning. Are you interested in merging this?

**Comment by rmachielse** [comment]
@alexblom do you have time to look at this soon? Would be greatly appreciated

**Comment by lougreenwood** [comment]
👍  looks like this fixes #9 too

**Comment by alexblom** [comment]
I dropped the ball n this one - will give it a QA tomorrow and otherwise merge. Thanks for doing this!

**Comment by rmachielse** [comment]
@alexblom no worries, glad you found time for this! I’ll rebase this tomorrow as well

**Comment by rmachielse** [comment]
@alexblom rebased!

**Comment by alexblom** [comment]
Thank you!

**Pull request merged**
